common:
  forward_host: 127.0.0.1
  forward_port: 8080
  socket_buf_size: 1024
rate_limit_algorithm: leaky bucket
token_bucket:
  periodic_second: 5
  n_tokens_to_be_added_per_periodic_second: 5
  token_bucket_size: 5
leaky_bucket:
  periodic_second: 5
  n_request_to_be_processed_per_periodic_second: 5
  request_queue_size: 5
